# Tensor Flow Tutorial

In [1]:
import tensorflow as tf

In [7]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]]) 
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [10]:
tf.matmul(t, tf.transpose(t))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [14]:
from tensorflow import keras
K = keras.backend
K.square(K.transpose(t))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1., 16.],
       [ 4., 25.],
       [ 9., 36.]], dtype=float32)>

In [15]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [16]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [17]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

# Huber loss in numpy

In [18]:
import numpy as np

def huberLoss_np(true, pred, delta):
    error = true-pred
    is_small_error = np.abs(error)<delta
    squared_loss = np.square(error)/2
    linear_loss = np.abs(error) - 0.5
    loss = np.where(is_small_error , squared_loss, linear_loss)
    return np.sum(loss)


def huberLoss_tf(true, pred, delta):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss  = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)
    